#   project euler
#   bradley smith
#   problem two
#   start: 1/10/2019
#   completed: 1/10/2019
#   language: python 2.7

#   problem statement:
#       each new term in the Fibonacci sequence is generated by adding the previous two terms. 
#       by starting with 1 and 2, the first 10 terms will be: 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
#       by considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.


def fibonacciSum(target):

    a = 0
    b = a + 1
    c = 0 
    fib = [a]

    while c < target:
        c = a + b 
        fib.append(c) 
        a = b 
        b = c 

    fibEvenValues = []

    for value in fib:
        if value % 2 == 0:
            fibEvenValues.append(value)

    print sum(fibEvenValues)

fibonacciSum(4000000)